spring:
  config:
    activate:
      on-profile: "user"
server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: "product"
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: "order"
server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: "batch"
server:
  port: 8083